version: '3.8'

services:
  postgres:
    image: postgres:16.4
    container_name: tmanager_postgres
    environment:
      POSTGRES_DB: tmanager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg_data:/var/lib/postgresql/pg_data
    ports:
      - "5432:5432"
    restart: always

volumes:
  pg_data: